import styles from './Projects.module.css'

function Projects() {
  return (
    <section id="projects" className={styles.section}>
      <div className={styles.inner}>
        <p className={styles.label}>Selected work</p>
        <h2 className={styles.title}>Things I've built.</h2>
        <p className={styles.subtitle}>
          Full-stack pet projects shipped from zero — real users, real feedback.
        </p>

        <div className={styles.grid}>

          {/* Featured — placeholder */}
          <article className={styles.cardFeatured}>
            <div className={styles.featuredVisual}>01</div>
            <div className={styles.featuredBody}>
              <div>
                <p className={styles.cardNumber}>Featured project</p>
                <h3 className={styles.cardTitle}>Project Name — Coming Soon</h3>
                <p className={styles.cardDesc}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
                </p>
                <div className={styles.tags}>
                  <span className={`${styles.tag} ${styles.tagAloe}`}>In progress</span>
                  <span className={styles.tag}>React</span>
                  <span className={styles.tag}>TypeScript</span>
                  <span className={styles.tag}>Node.js</span>
                </div>
              </div>
              <a href="#" className={styles.cardLink}>
                Coming soon
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <path d="M2 10 10 2M4 2h6v6" />
                </svg>
              </a>
            </div>
          </article>

          {/* Card 2 — Highlingua */}
          <article className={styles.card}>
            <p className={styles.cardNumber}>02</p>
            <div className={styles.cardIcon}>
              <img alt="" src="/highlingua.png"/>
            </div>
            <h3 className={styles.cardTitle}>Highlingua — AI Language Learning</h3>
            <p className={styles.cardDesc}>
              AI-powered flashcard app with 4 quiz modes, spaced repetition, activity calendar, and learning stats. Flashcards generated by Gemini 2.5 Flash.
            </p>
            <div className={styles.tags}>
              <span className={`${styles.tag} ${styles.tagAloe}`}>Live</span>
              <span className={styles.tag}>React</span>
              <span className={styles.tag}>Gemini AI</span>
              <span className={styles.tag}>PostgreSQL</span>
            </div>
            <div className={styles.cardLinks}>
              <a href="https://lnkd.in/e_HJkpdR" target="_blank" rel="noreferrer" className={styles.cardLink}>
                Live demo
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <path d="M2 10 10 2M4 2h6v6" />
                </svg>
              </a>
              <a href="https://lnkd.in/eEN4YNgz" target="_blank" rel="noreferrer" className={styles.cardLink}>
                GitHub
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <path d="M2 10 10 2M4 2h6v6" />
                </svg>
              </a>
            </div>
          </article>

          {/* Card 3 — Kanban */}
          <article className={styles.card}>
            <p className={styles.cardNumber}>03</p>
            <div className={styles.cardIcon}>
            <img alt="" src="/kanbloom-white.png"/>
            </div>
            <h3 className={styles.cardTitle}>Kanban Board</h3>
            <p className={styles.cardDesc}>
              First full-stack project. Drag and drop cards and columns, JWT auth with refresh tokens, dark/light theme. Monorepo with npm workspaces, deployed on Render.
            </p>
            <div className={styles.tags}>
              <span className={`${styles.tag} ${styles.tagAloe}`}>Live</span>
              <span className={styles.tag}>React</span>
              <span className={styles.tag}>Express</span>
              <span className={styles.tag}>PostgreSQL</span>
            </div>
            <div className={styles.cardLinks}>
              <a href="https://lnkd.in/eD_sbFmG" target="_blank" rel="noreferrer" className={styles.cardLink}>
                Live demo
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <path d="M2 10 10 2M4 2h6v6" />
                </svg>
              </a>
              <a href="https://lnkd.in/ednynYMc" target="_blank" rel="noreferrer" className={styles.cardLink}>
                GitHub
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <path d="M2 10 10 2M4 2h6v6" />
                </svg>
              </a>
            </div>
          </article>

        </div>
      </div>
    </section>
  )
}

export default Projects